### ISSUE TITLE
Prism with visrep model

### ISSUE THREAD

**Issue by long21wt** [thompsonb/prism#14]
Hi,

I wonder, Could we use prism with visrep model from https://github.com/esalesky/visrep? Or do you have any direction to integrate it in prism?
Since both are built on fairseq, I think it would be really great to combine the two works to form a new metric that is essentially robust to orthographic adversarial attacks.

**Comment by thompsonb** [comment]
I don't have any plans to try it but I don't see any reason why it wouldn't work.
