### ISSUE TITLE
All optional arguments invalid for generate_paraphrases.py

### ISSUE THREAD

**Issue by MeDarina** [thompsonb/prism#16]
I would like to have paraphrases generated.
I followed all the instructions (installed the main - the metric worked in the command line; ran the fairseq preprocessing - test_bin was generated)
Now when I run the generate_paraphrases.py, I get "error: argument --X: invalid Optional value: 'Y'" for all the optional values that I put in the call (e.g. "generate_paraphrases.py: error: argument --batch-size: invalid Optional value: '8'; generate_paraphrases.py: error: argument --path: invalid Optional value: '../m39v1/checkpoint.pt')

I tried to debug and as far as I see, the arguments are not passed to the parser (it breakes at "args = options.parse_args_and_arch(parser)" in generate_paraphrases.py. 

Do you have any tip for me how to adjust the code so I can pass the arguments properly? (I would also be happy to try "hard-code" the arguments somewhere and then work further from that point)

(I am working on a MacOS Monterey 12.3.1; in PyCharm (in the terminal))

**Comment by thompsonb** [comment]
Can you verify that your fairseq version matches the version in requirements.txt? 
`import fairseq`
`print(fairseq.__version__)`

**Comment by MeDarina** [comment]
Thanks, that was the issue, I had a newer version!
