### ISSUE TITLE
support multiple paraphrases per one sentence?

### ISSUE THREAD

**Issue by aosokin** [thompsonb/prism#8]
Hi, does your method and code support generating several different paraphrases of one input sentence?
Best,
Anton

**Comment by thompsonb** [comment]
Hi Anton, our method doesn't address diverse beam search, but Fairseq implements Vijayakumar et al., 2016.  We implement the n-gram down-weighting as a stand-alone "model" and ensemble it with the MNMT model, so you can combine our method with diverse beam search easily:
```python generate_paraphrases.py test_bin --batch-size 8    --prefix-size 1    --path $MODEL_DIR/checkpoint.pt    --prism_a 0.006 --prism_b 4  --diverse-beam-groups 5 --diverse-beam-strength 0.5 --beam 5 --nbest 5 ```

**Comment by aosokin** [comment]
Thanks a lot, this works great!
