### ISSUE TITLE
Potential extension of PRISM ? (collaboration?)

### ISSUE THREAD

**Issue by PierreColombo** [thompsonb/prism#9]
Hello,
Thanks for your work !  I hope you are doing well :-) . We read your papers and would like to build on your work.

I would like to better understand your tokenizer choice. Why did you choose the sentencepiece ? 
Another question I had, how costly is it to retrain your translation model ? 
Are you currently working on extensions of this work ? 
Cheers,
Pierre

**Comment by thompsonb** [comment]
The main reason we use subwords is to make the vocabulary size reasonable. For the advantages of sentencepiece, I will refer you to their paper: https://aclanthology.org/D18-2012

We describe the cost of training Prism on AWS in our paper (https://aclanthology.org/2020.emnlp-main.8/) - see Appendix C. 

I am not currently working on any extensions but Google had success training a larger model: https://aclanthology.org/2021.naacl-main.91/

**Comment by PierreColombo** [comment]
Many thanks for the response :)
